### ISSUE TITLE
Remove ["<", ">"] from the autoClosingPairs and surroundingPairs in clarion.configuration.json

### ISSUE THREAD

**Issue by msarson** [fushnisoft/SublimeClarion#6]
This pair is fine as Brackets, however for autoclosing or surrounding pairs it causes issues.

Consider the clarion code

IF A < B

With the current setting, as you type you get

IF A <> B

**Comment by fushnisoft** [comment]
done, sorry. I had not considered that at all! I did look to see if there was a way to only autoClosingPairs when in a string literal but it was not obvious and I gave up.
